### ISSUE TITLE
Question about adding audio

### ISSUE THREAD

**Issue by benjamin-zimmerman** [pstefa1707/multiplayer-pong#2]
Hi and thank you for creating this lovely game. 

I forked the project and am trying to add sound effects when the ball hits the paddles, or when an opponent scores. I'm newer to programming with node.js, and I'm a bit confused about where I should put what code.

-----------------------------------------------
I was thinking something along the lines of adding to client.js in /public

`var sound1 = new Audio(/my/audio/file.mp3);
socket.on('play-audio', function() {
             sound1.play()
});`

but then I'm not sure where I add code to emit the play-audio function.

No worries if you're done working on this project! I just thought I'd ask.

**Comment by benjamin-zimmerman** [comment]
Okay, I figured this out. I put a flag in the Game.js code, and then emit an event in the Client.js file.

Great game!

**Comment by pstefa1707** [comment]
Hi Ben,


I found it awesome that someone is using my project! Let me know how it works out for you.


I don't use this email much, contact me on discord @pstefa#8587 for any questions.


Thanks, Paras.

?

________________________________
